webtalk_init -webtalk_dir C:/Users/anjan/OneDrive/Desktop/New folder/Processor/Processor/Processor.sim/sim_1/behav/xsim/xsim.dir/clock_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jul  1 20:12:42 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f407e30a-94de-4d11-a391-7c5001ecdd85" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d0d3335672ff45e8924c2a077ac733f2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "62" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "18" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "4074 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "424 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "90" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "19" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "182.87_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "8919852_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2741264654 -regid "" -xml C:/Users/anjan/OneDrive/Desktop/New folder/Processor/Processor/Processor.sim/sim_1/behav/xsim/xsim.dir/clock_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/anjan/OneDrive/Desktop/New folder/Processor/Processor/Processor.sim/sim_1/behav/xsim/xsim.dir/clock_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/anjan/OneDrive/Desktop/New folder/Processor/Processor/Processor.sim/sim_1/behav/xsim/xsim.dir/clock_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
